### ISSUE TITLE
Create Initial condition

### ISSUE THREAD

**Issue by eropanda** [N-BodyShop/gasoline#10]
How can I create a new initial condition like AGORA.bin?
pyICs? or...
Although I have used pynbody to look inside the AGORA.bin,
I do not completely understand the data structure and how to create it.
Could I get some suggestion from you to handle this initial condition problem? 
Thank you.

**Comment by trquinn** [comment]
See https://github.com/N-BodyShop/changa/wiki/File-Formats for documentation on the data structure.

There are a few codes out there that will generate ICs suitable for Gasoline and ChaNGa.  pyICs will create isolated halos.  MUSIC by Oliver Hahn will create cosmological zoom ICs.

This needs to be added to the Wiki documentation.

**Comment by chreinhardt** [comment]
Lets not forget: [ballic](https://github.com/chreinhardt/ballic) (Reinhardt & Stadel 2017) which creates very low noice particle representation of (proto) planets :)

**Comment by trquinn** [comment]
Excellent.  And [diskpy](https://github.com/ibackus/diskpy) for protoplanetary disks.

**Comment by stadel** [comment]
Also like MUSIC, Doug has a code called Grafic++ which is a high
performance version for zooms. (2LPT)

And there is also PKDGRAV3 which generates ICs as well. Particularly
interesting is its recent coupling to CLASS to generate precision ICs for
Cosmology runs (incl massive neutrinos and DE fluctuations). It can output
in Tipsy only, at the moment. (2LPT)

Joachim

**Comment by eropanda** [comment]
I will try to understand how do those I.C. generator work.
Thank you all very much.

**Comment by trquinn** [comment]
Another one for isolated halos: [ICIng](https://github.com/mtremmel/ICInG)

**Comment by trquinn** [comment]
I've put all these suggestions in https://github.com/N-BodyShop/changa/wiki/Creating-Initial-Conditions

Feel free to reopen if you think of others.
