### ISSUE TITLE
problem of feeding the product of pytipsy to gasoline

### ISSUE THREAD

**Issue by eropanda** [N-BodyShop/gasoline#11]
I use pytipsy to create a tipsy structure file, 'ICtest'
ICtest can be read by pytipsy and pynbody.
and the header of ICtest is
{'ndim': 3, 'nstar': 27, 'ngas': 27, 'time': 1.0, 'n': 81, 'ndark': 27}.

but when I use gasoline to run a simulation by setting ICtest as initial condition.
it shows
Input file, Time:3.03865e-319
Simulation to Time:0.5
Reading file...
N:1358954496 nDark:452984832 nGas:452984832 nStar:452984832 Time:3.03865e-319
gasoline: pkd.c:186: pkdInitialize: Assertion `pkd->pStore != ((void *)0)' failed.
Aborted (core dumped)

the parameters that gasoline shows are totally different from what I set.
If I want to let gasoline read the parameters that I set in ICtest correctly.
What should I do?
Hope someone can help me to fix this problem.
Thank you.

**Comment by trquinn** [comment]
Quick suggestion: try setting "bStandard = 1" in your parameter file.

**Comment by eropanda** [comment]
After I add "bStandard = 1" to the parameter file, it starts working.
Thank you very much.
but what is the meaning of "bStandard = 1"?
I do not see it in the ChaNGa Options.

**Comment by trquinn** [comment]
There are two main ways of storing binary data on disk: "big endian" and "little endian".  The tipsy format was developed when "big endian" was common (the "standard" format), but now "little endian", used by Intel, dominates.  I'll fix the documentation.

**Comment by trquinn** [comment]
Documentation added.
