### ISSUE TITLE
the -np flag

### ISSUE THREAD

**Issue by N-body-group-Reed** [N-BodyShop/gasoline#12]
I am a neophyte in with gasoline, but have some experience with submitting ChaNGa programs via sbatch.  The meaning of the -np flag on the gasoline wiki  seems to be "the number of cores."

On p. 170 of Pitt-Francis's, Springer book the -np flag is referred to the "number of processes," which those authors distinguish from number of processors. And, it seems reasonably clear that the number of processors is different than the number of cores. Any hints.

Thanks in advance and for the excellent N-body software and agora initial conditions,

johnny powell
physics 
Reed College

**Comment by trquinn** [comment]
Process: a software concept, a program with a single address space and one or more threads of control.
Processor: a hardware concept that is a little nebulous, generally refers to a single die on which is etched one or more cores each containing one or more integer and floating point units.
For the MPI version of gasoline, each process has only one thread of control, so it makes sense to assign one process to each core.  In contrast, ChaNGa can (with the SMP build of charm) run with multiple threads per process, so it sometimes (but not always) is better to have one process per processor with one thread for each core.
