### ISSUE TITLE
Compilation crashes when without cooling

### ISSUE THREAD

**Issue by biernackip** [N-BodyShop/gasoline#5]
Compilation crashes if cooling is disabled at compilation level. Code was just cloned from the repository.
```bash
gcc -O3 -I../mdl/null  -DNOCOOLING -DGALAXY 			 -DWENDLANDC4                -c -o main.o main.c
In file included from pst.h:5:0,
                 from master.h:5,
                 from main.c:12:
pkd.h:128:5: error: unknown type name ‘COOLPARTICLE’
     COOLPARTICLE CoolParticleHot;  /* Abundances and any other cooling internal variables */
     ^
pkd.h:394:5: error: unknown type name ‘COOLPARTICLE’
     COOLPARTICLE CoolParticleHot;  /* Abundances and any other cooling internal variables */
     ^
<builtin>: recipe for target 'main.o' failed
```

**Comment by bwkeller** [comment]
Hi Pawel,

Thanks for the bug report, I've taken a look at the code, and there is some good news and bad news.  The bad news is that fixing this will be a huge pain.  The good news is that it doesn't matter, you can still run without cooling.  There are two ways in which cooling can be disabled: at compile time or at run time.  The compile-time method strips out every bit of cooling related code, of which a lot of the *other* code relies (star formation, feedback, etc.).  

Getting the basic "galaxy physics" modules to compile without cooling enabled will require a lot of re-writing.  Luckily, you can still compile with any of the other cooling modules (I typically use COOLING_METAL for most of my runs), and then disable cooling by adding bGasAdiabatic = 1 and bGasCooling = 0 in your parameter file.  This will run with purely adiabatic gas, without running into the issue you've seen.

I've stripped this option out of the default Makefile, this older method of disabling the cooling is now considered deprecated.  If you need to turn off cooling, just add the lines I mentioned above to your parameter file.  Thanks again for the bug report.

Ben

**Comment by biernackip** [comment]
Hi Ben,

Thanks! I am aware that there are other ways, but as this was one way to achieve what I needed and not working, then I thought it might be a good idea to let you know about this little inconsistency.

Thanks for the hint on how this is practically set up.

Pawel
