### ISSUE TITLE
pst.c:1254: _pstRootSplit: Assertion `nHighTot <= nUpperStore' failed

### ISSUE THREAD

**Issue by aatrani** [N-BodyShop/gasoline#6]
Isothermal runs, compiled with:
-DGASOLINE
-DGDFORCE
-DNSMOOTHINNER
-DCULLENDEHNEN

Parameter file attacched:
[up_param.txt](https://github.com/N-BodyShop/gasoline/files/1602374/up_param.txt)

Code was modified to include a custom external potential (using pkdHernquistSpheroid) and to keep an smbh particle fixed at origin.

Snapshot before crash here 
http://gofile.me/2BZkg/7LlIjJDZV

Any suggestion?
Alessandro

**Comment by trquinn** [comment]
This is a failure in domain decomposition.  Experiment with "dExtraStore" to change the memory constraints.  Increasing dExtraStore is most likely to help.

**Comment by aatrani** [comment]
Thanks, it worked
