### ISSUE TITLE
How to run example simulation?

### ISSUE THREAD

**Issue by 8la888** [N-BodyShop/gasoline#8]
after "cp Makefile.default Makefile",
I "make null" and put "agora.param", "AGORA.bin" in the "gasoline" folder,
then, "./gasoline agora.param",

I got the response below:
GASOLINE running on 1 processor.
Input file, Time:1
Simulation to Time:51
Reading file...
N:312500 nDark:100000 nGas:100000 nStar:112500 Time:1
Could not open ./AGORA.bin.MassHot,  skipped.
Could not open ./AGORA.bin.uHot,  skipped.
Could not open ./AGORA.bin.igasOrder,  skipped.
Could not open ./AGORA.bin.coolontime,  skipped.
WARNING: Could not open redshift input file:./agora.red
gasoline: cooling_metal.c:265: clReadMetalTable: Assertion `fp != NULL' failed.
Aborted (core dumped)

How can I fix this problem?
Thank you very much.

**Comment by trquinn** [comment]
It is looking for the "cooltable_xdr" file which is in the "data" subdirectory.   Copy that file into the folder in which you are running gasoline.

**Comment by 8la888** [comment]
I got it.
I have started to run the example.
Thank you so much.
