### ISSUE TITLE
After running example...

### ISSUE THREAD

**Issue by 8la888** [N-BodyShop/gasoline#9]
I have completed my first test of running the example, "Agora"
and ...
if I want to run my own simulation by GASOLINE,
that means I need
initial condition: "tipsy format",
parameter file: "txt format",
Makefile is some kind of function control panel
Do I understand GASOLINE correctly?

if I want to do movie to visualize the example "Agora"
I just need to add some parameters below ?
dDumpFrameTime = 0.1
dDumpFrameStep = 500
Should I change the default value of output visualization option of Makefile?

Is there any other suggested method to visualize the output file of simulation?

**Comment by bwkeller** [comment]
If you want to analyze the outputs (make plots, etc.)  I would recommend
using pynbody (pynbody.github.io).  It can load tipsy format snapshots,
plot slices and projections, and also build new ICs if you need as well.
Good luck, happy running!

**Comment by trquinn** [comment]
And you can always use "tipsy": https://github.com/N-BodyShop/tipsy.  Only recommended for old-timers!

**Comment by 8la888** [comment]
I have used pynbody to load files,
and I think it is helpful to me.
Thank you all for your recommendations.

By the way, should I deal with the environment varible problem below ?
"PKDGRAV_CHECKPOINT_FDL environment variable not set"

**Comment by bwkeller** [comment]
you should set that to point at wherever you have the "checkpoint.fdl" file
in your gasoline repository stored.  It defines the layout of the
checkpoint files, which will let you resume a simulation.

**Comment by 8la888** [comment]
I got it 
Thank you for helping me to deal with this problem.
